### ISSUE TITLE
"Medium" Branding Option and Clarifying How to Brand

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/brand#1]
@kathy-phet requested that we have an intermediate option for branding that says something like "adapted from" and the PhET logo in black and white (slightly different than shown in the email below)

We also want to make clearer for users when and how they show brand our sims when they for them.
## Kathy's email is copied below for reference:

Hi Sam,

I just got off Skype with ----.

He is largely using our sims as is, and is planning to make only very small changes from the original design. In build an atom for instance his publisher wants to add another ring to the atom so their are 3 levels instead of just 2. He changed the brand based off of our text in the "Brand" repo. He recommended we add some text there describing in more detail about when changing the brand was appropriate, and when it was not.

My recommendation is that we provide folks like him with an intermediate that says something like this ...

![brand](https://cloud.githubusercontent.com/assets/4051174/5541656/f39593ca-8a98-11e4-892d-563db70ed8cc.png)

And we make some change in what the "About" dialog says something similar.

He is working for a company called ------------- in Spain. ---------  seemed to very much want to do what ever we would prefer and then present that to his company.

So we should discuss how to proceed.

He is interested in using _all_ of the simulations we already have ... he even mentioned some that are not done. I mentioned that we would really want him to hold off on publishing sims that have not fully gone through our testing process. He seemed interested in helping out in terms of fixing bugs and such. I'm not sure of his skill level, but he says he has learned so much by looking at how we do our "magic".

He has forked everything, I believe. You can find his git hub account below in the chat feed.

He also made a translation utility below for his publisher ... he would be happy to share with us, if helpful at all. He has several languages he needs these to be in.

Best,
Kathy

**Comment by samreid** [comment]
[from email]

Sounds good.  Can we discuss timing and prioritization?  Does ------'s group have a specific publication timeline when they will be making these public (or are they already)?  Also, do you want to i18nize the "Adapted from" text?  May be odd for the entire sim to be in Spanish except for that text?

If it is not a "rush job" perhaps it would be good to schedule a time slot for this on Thursday for discussion?

**Comment by samreid** [comment]
@ariel-phet responded:

> Hey Sam,
> 
> I have it on the agenda for Developer meeting after the New year.
> 
> Ariel

**Comment by samreid** [comment]
@ariel-phet said we should i18nize that "adapted from" text and put the logo in black + white (and one that works against a white background).  Probably "adapted from" will be on 2 lines.

@ariel-phet also said, we could put the "adapted from" outside of the logo.

@ariel-phet maybe some documentation about this in the brand repo.

**Comment by samreid** [comment]
We need to decide how this should work technically--whether it will be a branch or another repo, or something else.

**Comment by samreid** [comment]
Next step is for @ariel-phet to get some artwork.  I can work on this after I get back from conference next week.

**Comment by ariel-phet** [comment]
@samreid see the mockups below. 

If you need the PhET logo in the two different black and white version shown below, email @amanda-phet and give her the specifications for what you need.

![homescreen mockup-04](https://cloud.githubusercontent.com/assets/4051174/5706561/2a7de490-9a3f-11e4-833b-d8c530556278.jpeg)
![homescreen mockup-03](https://cloud.githubusercontent.com/assets/4051174/5706564/2cee7f78-9a3f-11e4-895a-1acda5fcde42.jpeg)

**Comment by samreid** [comment]
@ariel-phet What do you want to do with the splash screen?  If we do nothing else, it will be blank (the default for brand).

**Comment by samreid** [comment]
@ariel-phet: Also, should the "adapted from" text be part of the PhET button?  I was planning on not, but just thought I'd double check.

**Comment by samreid** [comment]
joist's ohtwo branch will be merging to master on Jan 20.  If we do this work before then, it will have to be ported to ohtwo properly and retested after merge.

**Comment by samreid** [comment]
Running into complication because of how the PhETButton is handled differently in the navbar vs homescreen--same scales are giving different text stroke thickness.

**Comment by samreid** [comment]
I have pushed initial work on this issue, but there is a serious issue noted in the AdaptedFromPhETText.js

``` js
  // TODO: This next line is causing problems.  When using Futura/bold the text looks the same on homescreen vs navbar
  // TODO: on Chrome.  On Firefox it is very blurry!  Changing font makes it render differently on homescreen vs navbar.
  var font = new PhetFont( { family: 'Futura', size: 9, weight: 'bold' } );
```

@jonathanolson's help could be invaluable here.

**Comment by samreid** [comment]
Also note: the selected font above looks horrible in Firefox

**Comment by samreid** [comment]
@ariel-phet Should we add any changes to the About dialog?  How about adding a link to the PhET homepage in the menu?

**Comment by samreid** [comment]
@ariel-phet I have finished preliminary work on this.  Should we set up a way for you to review it?  I think 3rd parties could start using it soon if we want.

**Comment by samreid** [comment]
Assigned to @ariel-phet based on the above comment.  I'm still on leave--perhaps another developer can review what was done here and make it available for you to test out.

**Comment by pixelzoom** [comment]
Some of this work has been done. The remainder moved to https://github.com/phetsims/brand/issues/18. Closing.
