### ISSUE TITLE
insufficient doc for Brand.js fields

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/brand#10]
Here's what doc looks like for Brand.js fields in 'master':

``` js
  return {
    name: null, // {string} For example: 'My Company'
    copyright: null, // {string} For example: 'Copyright © 2014, My Company'
    links: null, // {Object[]} For example: { text: 'My Company Support', url: 'https://www.mycompany.com/support' }
    adaptedFromPhET: false // {boolean} is this brand adapted from PhET?
  };
```

This tells us nothing about where these strings and links will actually appear, what happens when adaptedFromPhET is true, etc.  One must resort to searching the code for occurrences of these fields. For example, only by searching for "links" did I discover that the links are added to the bottom of the About dialog.

**Comment by samreid** [comment]
Note that `adaptedFromPhET` is no longer used and an `id` field is used instead, see https://github.com/phetsims/joist/issues/271

**Comment by samreid** [comment]
I started augmenting the documentation like so:

``` js
    // Nickname for the brand, which should match the brand subdirectory name, grunt option for --brand as well as the
    // query parameter for ?brand.  This is used in Joist to provide brand-specific logic, such as what to show in the 
    // about dialog, decorative text around the PhET button, and whether to check for updates.
```

However, duplicating that in all of the Brands seemed like an anti-pattern.  Perhaps it would be best to factor this out into a Brand superclass or auxiliary function, even if only to factor out the documentation?

**Comment by samreid** [comment]
Well, factoring this out looks like it would mean _another_ entry in the config.js files.  We currently have:

`BRAND: '../../brand/' + phet.chipper.brand + '/js',`

We could possibly have a BRAND and SELECTED_BRAND or something like that, but I'm not too sure about it.  @pixelzoom can you please advise?

**Comment by pixelzoom** [comment]
Discussed with @samreid via phone.

Put bulk of the documentation in 'adapted-from' brand.  

Describe how to modify 'adapted-from' brand to create a custom brand, mention that Brand.name must be changed if you want to get rid of the "Adapted from" in the navbar.

**Comment by samreid** [comment]
> Put bulk of the documentation in 'adapted-from' brand.

and link to this doc from the other brands.

> Describe how to modify 'adapted-from' brand to create a custom brand, mention that Brand.name must be changed if you want to get rid of the "Adapted from" in the navbar.

This should be done in the readme, see #21

**Comment by samreid** [comment]
Fixed above.  Anything else to do here @pixelzoom ?

**Comment by pixelzoom** [comment]
:+1: Closing.
