### ISSUE TITLE
change brands to use new licensing URL

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/brand#12]
'phet' and 'interoperable' branches use this URL for licensing in Brand.js:

`url: 'http://phet.colorado.edu/en/html-terms-privacy-and-licensing'`

When the website is updated, this should be change to the new URL.

**Comment by pixelzoom** [comment]
7/16/15 status meeting, request by @kathy-phet:

• Use the correct URL in Brand.js (URL to be determined)
• Put up the webpage, even if it's a copy of what currently exists.
• Maintain redirect for old URL
• Required for "Summer 2015 redeploy"

**Comment by aaronsamuel137** [comment]
I put the licensing at the new url: licensing/html and added a redirect. We discussed potentially using a different url, but since there wasn't one decided upon I went with the existing thought of licensing/html.

**Comment by pixelzoom** [comment]
@aaronsamuel137 make sure you update the all branches of Brand.js that use this URL.

**Comment by samreid** [comment]
> We discussed potentially using a different url, but since there wasn't one decided upon I went with the existing thought of licensing/html.

I know there was some dissent at yesterday's meeting, but I wanted to throw in my $0.02 and say I think licensing/html will be good.

**Comment by aaronsamuel137** [comment]
Forgot to reference commit on branch phet: 3c45cb6fe87c342c377a90453be9fa8649818f59

**Comment by aaronsamuel137** [comment]
This should be ready to go, assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
I don't see the correct URL indicated anywhere in this issue, so I'm assuming that http://phet.colorado.edu/en/licensing/html is the correct URL.  Assigning back to @aaronsamuel137 to verify. If that's the correct URL, then go ahead and close this issue.

**Comment by aaronsamuel137** [comment]
Yep that's correct. Closing.
