### ISSUE TITLE
logos needed for 'interoperable' brand

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/brand#14]
As noted in https://github.com/phetsims/joist/issues/258#issuecomment-120543577, the logos for the 'interoperable' brand are currently the same as the 'phet' brand.  According to @ariel-phet this should be changed.

**Comment by samreid** [comment]
I believe this is being worked on in https://github.com/phetsims/tasks/issues/268 but good to track here as well (for integrating the completed artwork), so let's leave this open.

**Comment by pixelzoom** [comment]
This is being tracked in #4.
