### ISSUE TITLE
create an empty brand that 3rd parties can fill in

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/brand#18]
Decide what to call this brand.

**Comment by samreid** [comment]
Alternatively: make it trivial to modify the "adapted from PhET" brand to make it the client's brand and provide instructions on how to do so.

**Comment by samreid** [comment]
Two possibilities I see now:

(1) make it easy (and add instructions how) to modify the "adapted-from-phet" brand with the clients logo, etc.
(2) add instructions how the 3rd party can create their own subdirectory in brand, with their own company name.  For instance edubraintech (a company I just made up for this example) would create brand/edubraintech parallel to the other directories and use grunt options and requirejs parameters for testing.

I do like the symmetry of (2) but the ease of (1) for third parties might be a trump card.  Let's see what @pixelzoom @jbphet @jonathanolson @jessegreenberg and @aaronsamuel137 vote. 

Choosing randomly who to send the issue to:

``` js
_.sample('@pixelzoom @jbphet @jonathanolson @jessegreenberg @aaronsamuel137'.split(' '))
```

> "@pixelzoom"

**Comment by pixelzoom** [comment]
The correct thing to do would be to create your own brand, rather than perverting the "adapted-from" brand.  So I think we should steer people towards that by doing (2). Put instructions in master README.md.  That said... I'd bet most people will ignore the instructions and hack "adapted-from".

**Comment by pixelzoom** [comment]
I was going to take a stab at this, but the top-level README.md is gone. See https://github.com/phetsims/brand/issues/21

**Comment by samreid** [comment]
@pixelzoom & I discussed this and decided to document adapted-from-phet (the default) as the template for new brands.  I'll create a new issue about adding this documentation (if there isn't already one).

**Comment by samreid** [comment]
Added to #21 above, closing.
