### ISSUE TITLE
make 'adapted-from-phet' the default brand

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/brand#19]
Broke this issue out of https://github.com/phetsims/brand/issues/13.  

Until all brands are in master, this means moving the 'adapted-from-phet' branch to master.

**Comment by samreid** [comment]
@pixelzoom is this complete?

**Comment by pixelzoom** [comment]
No, hasn't been done.  Was potentially waiting until all brands are in master.  And doesn't need to be addressed for S2015R.

**Comment by samreid** [comment]
I'll be working on some other branding issue in the near future, so I'll assign this to me and take a look at it as well.

**Comment by samreid** [comment]
adapted-from-phet is now the default brand, and can be overriden with a grunt option --brand or a query parameter ?brand

Closing.

**Comment by pixelzoom** [comment]
Reopening. 

Did we bail on being able to specify the brand in $HOME/.phet/build-local.properties ?

**Comment by samreid** [comment]
We did not bail on being able to specify the brand in $HOME/.phet/build-local.json, it is being tracked and labeled for discussion at the next developer meeting in https://github.com/phetsims/brand/issues/11

Please close if there is nothing else to do for this issue.
