### ISSUE TITLE
changes for About dialog when unbranded or 'adapted from'

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/brand#2]
Should version number?

Should we append sim title with (adapted)

Other changes?

Link to the phet website?

**Comment by ariel-phet** [comment]
Lots of questions, should discuss with @kathy-phet

**Comment by ariel-phet** [comment]
@kathy-phet envisions unbranded being when people use our libraries/assets to make a pretty unique sim or a topic we do not cover. In this case, the about dialog should have some verbiage about powered by scenery with University of Colorado there, acknowledgement of PhET down near bottom of about dialog.

for medium branded sims: these include even just a major "paring" down of a sim, such as a much simpler version of say Under Pressure with a much limited control set. Initial thought is to have link to original sim in a phrase such as "adapted from Balancing Act", remove sims credits, let third party deal with version number and sim title, with link to PhET site and acknowledgment of PhET and CU Boulder.

Something like 
Sim Title (chosen by adapter)
Adapted from "Sim Name"
originally produced by PhET Interactive Simulations (TM), University of Colorado 
NO credits of our team or software agreement/licensing

**Comment by samreid** [comment]
Can you comment on priority?  If this is needed soon, perhaps it would be good for @aaronsamuel137 to take the lead.

**Comment by pixelzoom** [comment]
This issue is replaced by various other issues that discuss what specific brands look like. Closing.
