### ISSUE TITLE
Interoperable and adapted-from-phet branches failing build

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/brand#20]
Found while testing builds for review of phetsims/joist#163.  Logo images have the error "missing-license.json".  For phetsims/chipper#181, I notice that only the phet branch received the txt -> json conversion.

@samreid should interoperable and adapted-from-phet branches have the same (or similar) txt -> json license conversion?

**Comment by samreid** [comment]
Yes, thanks for pointing this out.  I'll take care of it shortly.

**Comment by samreid** [comment]
OK I updated the license files and tested that all 4 branches build properly with `grunt build-no-lint` in hookes-law.  Please report any other trouble you see.
