### ISSUE TITLE
Update the README.md file

### ISSUE THREAD

**Issue by samreid** [phetsims/brand#21]
From #11:
- Revisit the readme.md in https://github.com/phetsims/brand
- Maybe put a note that PhET is trademarked and can only be used with the expressed written consent.
- Put a comment in the phet brand that this is “hands off” federal trademarked one.

**Comment by samreid** [comment]
We should also indicate that the PhET logo (AI/PNG/SVG) does not fall under the MIT license.  In fact, I'm not sure what the best license for this repo is.

**Comment by pixelzoom** [comment]
README.md (and a bunch of other top-level files) appears to have disappeared.

**Comment by samreid** [comment]
Add documentation about how to create your own brand based on the adapted-from-phet one, from #18

**Comment by samreid** [comment]
I finished a rough draft here: https://github.com/phetsims/brand/blob/master/README.md

@pixelzoom can you take a look or delegate to someone else?

**Comment by pixelzoom** [comment]
Numerous tweaks to README files. Based to @samreid to review.  If these look OK, go ahead and close.

**Comment by samreid** [comment]
@pixelzoom's changes look good, thanks.  Closing.
