### ISSUE TITLE
top-level files missing from brand

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/brand#22]
Missing are:

README.md
.gitignore
LICENSE
package.json
Gruntfile.js

I realize that some of these moved into subdirs.  But we should still have these at top-level.

**Comment by pixelzoom** [comment]
The various subdirs should have their own README.md files that are specific to those brands. They currently look like identical copies.

**Comment by pixelzoom** [comment]
All 3 brand subdirs have MIT license in their LICENSE file. Can we move to a single LICENSE file at top level?

**Comment by samreid** [comment]
I restored these files, consolidated license files and added text about the image licensing in the README.  @pixelzoom can you take a look?

**Comment by pixelzoom** [comment]
Looks great.  Files can't be linted yet, but that's covered in https://github.com/phetsims/brand/issues/23.  

Closing.
