### ISSUE TITLE
rename 'interoperable' brand to 'phet-io'

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/brand#25]
8/6/15 dev meeting:
The public-facing logo for interoperable brands will be something like "PhET IO" or "PhET.io".  And it would be nice to have "phet" in the names of brands that are for exclusive use by PhET.  So we'll rename the 'interoperable' brand to 'phet-io'.

**Comment by pixelzoom** [comment]
Work completed. @samreid could you review?

**Comment by samreid** [comment]
The change sets seemed reasonable, I didn't see any stray occurrences of `interoperable` in the code and running neuron (built and non-built) versions with phet-io were both correct.  Closing.
