### ISSUE TITLE
add namespace

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/brand#26]
See https://github.com/phetsims/tasks/issues/378

**Comment by pixelzoom** [comment]
Hmmm.... This repo has no `js/` directory. Where to put `brand.js`?

**Comment by samreid** [comment]
My first instinct was to put a separate namespace under each of the brand/js dirs.  But upon reflection--does brand need to be on the namespace?  If so, why?

**Comment by pixelzoom** [comment]
> But upon reflection--does brand need to be on the namespace? If so, why?

Well, we decided to namespace all code that was namespace-able, but I guess we can revisit that. I guess one could argue that it might be useful to inspect `phet.brand.Brand` in the browser console.

**Comment by samreid** [comment]
The rule imposed by the ?checkNamespaces is that every requirejs module have a corresponding global, so for consistency we should namespace the Brand.

**Comment by pixelzoom** [comment]
It would be nice if we didn't have to duplicate `brand.js` in each of the subdirectories (adapted-from-phet/, phet/, phet-io/).  But I don't see how we can require `brand/js/brand.js` because require doesn't like relative paths.  Eg:

`var brand = require( 'BRAND/../../js/brand.js' );`

**Comment by pixelzoom** [comment]
Hmm... I tried the above require, and it actually works.  Guess I was mistaken about relative paths with require.

**Comment by pixelzoom** [comment]
I added namespacing using relative require paths. This seems a little iffy to me, so I'd like @samreid or @jonathanolson to have a look with high priority.

**Comment by pixelzoom** [comment]
Perhaps it would be safer to change add something like this to config.js:

`BRAND_ROOT: '../../brand',`

and require the namespace like this:

`var brand = require( 'BRAND_ROOT/brand.js' );`

**Comment by pixelzoom** [comment]
`BRAND` is currently set like this in config.js:

`BRAND: '../../brand/' + phet.chipper.brand + '/js',`

Perhaps it would be safer to add something like this to config.js:

`BRAND_ROOT: '../../brand',`

and require the namespace like this:

`var brand = require( 'BRAND_ROOT/brand.js' );`

... or maybe the relative path is OK?

**Comment by jonathanolson** [comment]
Another alternative is to have the brand namespace declared somewhere besides in brand, e.g. JOIST/brand.

I'm currently fine with either of the other described approaches, as long as it works in require.js and build mode.

**Comment by pixelzoom** [comment]
I tested the relative-path approach in both requirejs and build modes, didn't see any problems.

**Comment by pixelzoom** [comment]
12/3/15 dev meeting, we decided to go with the relative-path approach. Will revisit if it causes issues.
