### ISSUE TITLE
Animate loading screen

### ISSUE THREAD

**Issue by andrealin** [phetsims/brand#27]
@ariel-phet @amanda-phet and I discussed having some sort of animation on the loading screen. I'm thinking about something simple like rotating between "Loading" "Loading." "Loading.." and "Loading..."

Assigning to myself.

**Comment by samreid** [comment]
Our previous technical and design conversations about animating the loading screen (also called splash screen) are tracked over here: https://github.com/phetsims/joist/issues/68

**Comment by andrealin** [comment]
Closing this because it's a duplicate of phetsims/joist#68
