### ISSUE TITLE
About dialog shows stale copyright from brand

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/brand#31]
After publishing Unit Rates 1.0.0, I noticed that the copyright in the About dialog is out of date.  It still says "Copyright 2004-2016".   This will be wrong for any sims published so far in 2017 (Make A Ten, States Of Matter, States Of Matter: Basics,...)   The copyright currently lives in the brand repository, so adding this issue here.

There are 2 problems:

(1) How to keep the copyright up-to-date in brand. For now I will update the files.

(2) How to get the correct copyright date in maintenance releases.  Maintenance releases will currently be using some snapshot of the brand repository.  If that repository is earlier than the current year, then the copyright shown in the About dialog of the maintenance release will be incorrect.  For example, see [Arithmetic 1.0.7](https://phet.colorado.edu/sims/html/arithmetic/latest/arithmetic_en.html) currently live on the PhET website.  It's About dialog shows that it was built on 2017-03-07, but the copyright is "2004-2015" (from its version of brand).

Both of the above problems could be solved by having the build process insert the current year in the copyright.

Assigning to @ariel-phet to assign and prioritize.  Also labeling for discussion at developer meeting.

**Comment by samreid** [comment]
> having the build process insert the current year in the copyright.

We would have to make sure the clock on build server is right.  I vaguely remember once on one of phet's server it was way off.

**Comment by ariel-phet** [comment]
I will not be at dev meeting this week, but my 2 cents would be that inserting the current year in the build process seems like a good solution if possible - then it is automated and less likely to be missed.

**Comment by samreid** [comment]
Changing chipper to use current date for builds will still show wrong date for legacy maintenance deploys because they would be using old chipper.

**Comment by pixelzoom** [comment]
My opinion is that it would be fine to ignore this issue for legacy maintenance deploys, and address this "going forward".   ... unless there is some legal issue where CU cares about having the correct copyright in the About dialog.

Thinking out loud... Another place we could put the copyright is in package.json, under the "phet" data structure.  package.json is a file that needs to be modified anyway, to set the "version".   That's still prone to developer error, so I think having the build process automatically set it would be superior.  (And the clock on build-server should be correct regardless of this issue.)

**Comment by mattpen** [comment]
> We would have to make sure the clock on build server is right.

I think we can rely on the clock being correct for build-server for the purpose of this issue.  We are constantly recording timestamps for various activities on phet-server and it would be bad news for many urgent reasons if the clock is wrong.

**Comment by pixelzoom** [comment]
4/13/17 dev meeting:

Ask @kathy-phet whether this needs to be addressed.

**Comment by pixelzoom** [comment]
We're also wondering why the copyright is in brand.

**Comment by pixelzoom** [comment]
Questions for @kathy-phet:

(1) Should the copyright dates that appears in the About dialog be accurate for all published simulations? Or is it OK if the copyright dates are incorrect for simulations that are built with older shas? 

(2) Should the copyright be configurable based on brand, or should the copyright always be attributed to PhET regardless of brand?

**Comment by pixelzoom** [comment]
Feedback from @kathy-phet at status meeting:

• Continue to specify copyright in Brand
• Make copyright date accurate going forward.
• No need to address this for sims already published.

**Comment by pixelzoom** [comment]
Thoughts on how to address this...

Change `copyright` in Brand.js to:

```js
copyright: 'Copyright © 2004-{{year}} University of Colorado Boulder',
```

In AboutDialog.js,  use `StringUtils.fillIn` to replace `{{year}}`.  If it's a built version, get the year from `phet.chipper.buildTimestamp`.  Otherwise get the year from `Date.now`.

Questions:

(1) Should this only be done for `phet` and `phet-io` brands, or should we replace `{{year}}` if it's provided in `copyright` for any Brand?

(2) For built versions, is it safe to parse the year out of `phet.chipper.buildTimestamp`? E.g.:

```
> phet.chipper.buildTimestamp
"2017-04-18 15:39:14 UTC"
> phet.chipper.buildTimestamp.split( '-' )[0]
"2017"
```

(3) For requirejs mode, get year via `new Date().getFullYear()` ?

**Comment by jonathanolson** [comment]
> For built versions, is it safe to parse the year out of phet.chipper.buildTimestamp?

buildTimestamp is updated whenever translations are updated. Is that the desired behavior?

> For requirejs mode, get year via new Date().getFullYear() ?

Sounds good.

> Should this only be done for phet and phet-io brands, or should we replace {{year}} if it's provided in copyright for any Brand?

Seems simple to always replace.

**Comment by samreid** [comment]
There was a conversation long ago about changing copyright statements in our JS files from `2004-{{now}}` to `{{sim start date}}-{{now}}`.  Should the same be done for published sims?

**Comment by pixelzoom** [comment]
4/20/17 dev meeting

• @mattpen pointed out that every sim likely uses some piece of code who copyright is 2004.  So we'll go with `2004-{{year}}`.

• @jonathanolson pointed out it's actually `2002-{{year}}`, and I confirmed that `2002` appears in .js code.

• Replace `{{year}}` in all cases where `copyright` is provided in Brand.

**Comment by pixelzoom** [comment]
Implemented in above commit. 

I then tested the About dialog in Molarity, for all brands, in requirejs and built modes.  Screenshots:

requirejs mode, brand=phet:
![screenshot_222](https://cloud.githubusercontent.com/assets/3046552/25248125/5084d414-25ca-11e7-9505-fc7802bf2640.png)

requirejs mode, brand=phet-io
![screenshot_223](https://cloud.githubusercontent.com/assets/3046552/25248135/5c0d27be-25ca-11e7-9e00-9b57915fc05f.png)

requirejs mode, brand=adapted-from-phet:
![screenshot_224](https://cloud.githubusercontent.com/assets/3046552/25248144/6470002a-25ca-11e7-99a0-ecbd095a8e5f.png)

built, brand=phet:
![screenshot_225](https://cloud.githubusercontent.com/assets/3046552/25248169/77d39c44-25ca-11e7-8a69-04bbcfa411ea.png)

built, brand=phet-io:
![screenshot_226](https://cloud.githubusercontent.com/assets/3046552/25248182/7e940f3c-25ca-11e7-9322-fe0810084f12.png)

built, brand=adapted-from-phet:
![screenshot_227](https://cloud.githubusercontent.com/assets/3046552/25248189/86ad956c-25ca-11e7-9305-04448db4213d.png)

**Comment by pixelzoom** [comment]
```
> _.shuffle( [ 'JB', 'JG', 'JO', 'SR' ] )[0]
"JO"
```

Randomly assigned to @jonathanolson to review.

**Comment by jonathanolson** [comment]
Looks good to me.

Also a possibly-improved method for future assignment:
```js
_.shuffle( [ 'JO', 'JB', 'JG', 'SR' ].slice( 1 ) )[0]
```
;)
