### ISSUE TITLE
Transpiler doesn't visit newly added brands

### ISSUE THREAD

**Issue by samreid** [phetsims/brand#36]
As reported in the Google Group, the transpiler doesn't visit unknown brands: https://groups.google.com/g/developing-interactive-simulations-in-html5/c/m8VAhpZsC90

This makes it difficult for 3rd parties to add their own branding.

**Comment by samreid** [comment]
I added a `--brands` option so the transpiler can be invoked like so:

```
node js/scripts/transpile.js --brands=test-brand
```

This seems good enough for now, but eventually this should be integrated into the `grunt` process.

**Comment by vzrenggamani** [comment]
> I added a `--brands` option so the transpiler can be invoked like so:
> 
> ```
> node js/scripts/transpile.js --brands=test-brand
> ```
> 
> This seems good enough for now, but eventually this should be integrated into the `grunt` process.

Can you elaborate how to run this commands for the current version of the codebase please? thank you

**Comment by samreid** [comment]
Thanks, the transpiler now automatically transpiles all brands.  There is a community page linked from https://scenerystack.org/ if you have questions about how to access the latest code, how to add a brand, etc. Thanks! Closing.
