### ISSUE TITLE
decide what 'phet-io' brand looks like

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/brand#4]
@amanda-phet and @arouinfar - we should discuss some options for branding sims that have been outfitted with data collection.

@kathy-phet has suggested some modification of the PhET logo that includes the word "data" -- something that implies "PhET + data collection". If we come up with a preliminary idea, we can ask @mariahphet to implement it.

**Comment by kathy-phet** [comment]
Another option could also be the word "Interoperable" in front of and smaller than our logo, since that is what we have settled on for naming these sims.

Kathy

Sent from my iPhone

On May 26, 2015, at 5:58 PM, Ariel Paul <notifications@github.com<mailto:notifications@github.com>> wrote:

@amanda-phethttps://github.com/amanda-phet and @arouinfarhttps://github.com/arouinfar - we should discuss some options for branding sims that have been outfitted with data collection.

@kathy-phethttps://github.com/kathy-phet has suggested some modification of the PhET logo that includes the word "data" -- something that implies "PhET + data collection". If we come up with a preliminary idea, we can ask @mariahphet to implement it.

**Comment by pixelzoom** [comment]
Changed the name of this issue.

Includes:
• logos
• About dialog contents
• PhET menu items

**Comment by pixelzoom** [comment]
@kathy-phet Should this be labeled "Summer 2015 redeploy"? If we don't do it before then, we'll be stuck with English-only interoperable sims until we do another redeploy.

**Comment by pixelzoom** [comment]
@kathy-phet Never mind. We'll have to redeploy sims anyway to instrument them.  So this can wait.

**Comment by pixelzoom** [comment]
Changed issue title. Per #25, 'interoperable' brand was renamed 'phet-io'.

**Comment by amanda-phet** [comment]
Can this be closed? The logo has been decided on... is there more to do?

**Comment by pixelzoom** [comment]
As noted in https://github.com/phetsims/brand/issues/4#issuecomment-122046200, we also need to decide what items are in the PhET menu and what information is displayed in the About dialog.  I don't see anything above about those aspects.  So this issue should remain open.

**Comment by pixelzoom** [comment]
The PhET menu currently contains 2 items:

![screenshot_599](https://cloud.githubusercontent.com/assets/3046552/9693575/ab77c0f6-530e-11e5-9f9d-437f4c6170f5.png)

The About dialog currently looks like this:

![screenshot_600](https://cloud.githubusercontent.com/assets/3046552/9693587/c0d4249e-530e-11e5-8a15-bf63816b365a.png)

**Comment by amanda-phet** [comment]
Thanks, I didn't read the comments carefully enough. I will assign this back to @ariel-phet to decide how to move forward with this.

**Comment by pixelzoom** [comment]
For comparison, here are the PhET menu and About dialog for the 'phet' brand:

![screenshot_601](https://cloud.githubusercontent.com/assets/3046552/9693667/646f2568-530f-11e5-829d-a99f84e6a86f.png)

![screenshot_602](https://cloud.githubusercontent.com/assets/3046552/9693668/677ed6cc-530f-11e5-8ec7-5c01df45cb9e.png)

**Comment by pixelzoom** [comment]
At 9/17/15 interoperability meeting, @kathy-phet asked that this issue be assigned to her.

**Comment by pixelzoom** [comment]
@ariel-phet @samreid It seems like this has been done.  Can this issue be closed?

**Comment by samreid** [comment]
We now have the PhET-iO logo/splash screen and some additional text in the about dialog:

![image](https://user-images.githubusercontent.com/679486/50598054-c53be280-0e66-11e9-8a76-9a059be65dfb.png)

I'm not aware of more planned work along these lines, leaving assigned to @ariel-phet to comment.

**Comment by ariel-phet** [comment]
Everything here seems pretty settled for the moment, I imagine any tweaks to the brand are more appropriate for specific polish issues in the future. Closing.
