### ISSUE TITLE
branch: adapted-from-phet

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/brand#5]
@samreid or @jbphet Can you please document this branch?

**Comment by pixelzoom** [comment]
Reassigning this to @samreid, since he appears to have created this branch and made most of the commits.

**Comment by samreid** [comment]
This branch is for groups that are making "Adapted from PhET" branded sims.  This branch can be deleted and the issue closed when we complete: https://github.com/phetsims/brand/issues/11.  Unassigning.

**Comment by pixelzoom** [comment]
@samreid The 'phet' and 'interoperable' branches have been deleted. Can this branch also be deleted?

**Comment by samreid** [comment]
Yes, I just deleted it. Closing.
