### ISSUE TITLE
branch: phet

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/brand#8]
This branch contains the "PhET" brand.  It was migrated from phetbrand/brand 'master' branch.

**Comment by pixelzoom** [comment]
This branch should be deleted when all brands are moved to master, see #11.

**Comment by samreid** [comment]
All brands got moved to master yesterday, but I'd like to look around the other branch issues before deleting these branches. Reassigning to myself.

**Comment by samreid** [comment]
I can't think of anything else we will need from this branch.  I'll delete it.

**Comment by samreid** [comment]
The `phet` branch is gone.  Closing.
