### ISSUE TITLE
branch: interoperable

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/brand#9]
The "together" branch contains the brand for interoperable PhET sims. It was migrated from phetbrand/brand 'together' branch.

**Comment by pixelzoom** [comment]
Renamed this branch to "interoperable".

**Comment by pixelzoom** [comment]
This branch should be deleted when all brands are moved to master, see #11.

**Comment by samreid** [comment]
All brands got moved to master yesterday, but I'd like to look around the other branch issues before deleting these branches.  Reassigning to myself.

**Comment by samreid** [comment]
I can't think of anything else we will need this branch for.  Deleting and closing.
